[package]
name = "tcpping-common"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }

[lib]
name = "tcpping_common"
path = "src/lib.rs"
